name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          node-version: '16' # Spécifiez la version 16 de Node.js

      - name: Install dependencies
        run: npm install

      - name: Prettier
        run: npm run prettier:check

      - name: ESLint
        run: npm run lint

      - name: Run Jest tests
        run: npm test

      - name: Check Jest coverage
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - run: echo " The workflow is now ready to test your code on the runner. "

      - name: Display start time
        run: echo "Start time: $(date)"
