name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'


    - name: Install dependencies
      run: npm install


    - name: Display start time
      run: echo "Start time:$(date)"


    - name: Format code with Prettier
      run: npm run prettier --write .


    - name: Lint code
      run: npm run eslint --fix .


    - name: Run Jest tests with coverage
      run: npm test -- --coverage


    - name: Display end time
      run: echo "End time:$(date)"


    - name: Display success message
      run: echo "PIPELINE SUCCESS WITHOUT ERRORS"